name: Quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quality:
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
